### ISSUE TITLE
Opening a serial port doesn't write DTR command to the port

### ISSUE THREAD

**Issue by timleg002** [de-vri-es/serial2-tokio-rs#5]
This affects Windows. The serialport [serialport](https://github.com/serialport/serialport-rs) library fixed this, but it, of course, requires an additional dependency on a WinAPI crate.

This is a quite ugly workaround for this issue without fixing this library itself.

```rust
        // first we open the port using the serialport library
        let mut alt_serial_port = serialport::new(com_port, BAUD_RATE)
            .timeout(Duration::from_millis(10))
            .open()?;

        alt_serial_port.write_data_terminal_ready(true)?;

        // for some reason we can't close it normally...?
        std::mem::drop(alt_serial_port);
        
        // now we open the actual serial port we will use
        let serial_port = SerialPort::open(com_port, |mut settings: Settings| {
            settings.set_baud_rate(BAUD_RATE)?;
            Ok(settings)
        })?;
``` 

The `serialport` library uses this WinAPI function for this: [EscapeCommFunction](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-escapecommfunction)

**Comment by de-vri-es** [comment]
Hey! Why don't you use [`SerialPort::set_dtr(true)`](https://docs.rs/serial2-tokio/latest/serial2_tokio/struct.SerialPort.html#method.set_dtr)?

I see that you expect the opening of the serial port to set the DTR line automatically. I'm not convinced that should be the default. There are some weird use cases for using those pins as general purpose I/O pins. So doing anything with them automatically feels wrong.

Is there any reason that manually setting `DTR` with the function linked above is not good enough?
